linters:
  enable:
    - errcheck
    - govet
    - staticcheck

run:
  timeout: 5m

issues:
  exclude-dirs:
    - "/opt/hostedtoolcache/go/.*" # Exclude standard library directories
  exclude-rules:
    - path: ".*src/.*" # Exclude standard library files
      linters:
        - govet
